name: Build APK
on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "android-build"

      - name: Install cargo-ndk
        run: |
          if ! command -v cargo-ndk &> /dev/null; then
            cargo install cargo-ndk
          fi

      - name: Build Rust Lib (Release)
        run: |
          # Install platform secara paksa
          sdkmanager "platforms;android-33"
          
          # Set variabel untuk shell ini
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export ANDROID_PLATFORM=android-33
          # Path absolut ke android.jar (ini yang dicari Slint)
          export ANDROID_JAR=$ANDROID_HOME/platforms/android-33/android.jar
          
          # Daftarkan ke environment GitHub agar Cargo NDK bisa baca
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_JAR=$ANDROID_JAR" >> $GITHUB_ENV
          
          mkdir -p app/src/main/jniLibs/arm64-v8a
          cargo ndk -t arm64-v8a -o app/src/main/jniLibs/ build --release

      - name: Build APK with Gradle (Release)
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Set Build Tools Path
        run: |
          BUILD_TOOLS_VERSION=$(ls $ANDROID_SDK_ROOT/build-tools/ | tail -n 1)
          echo "ANDROID_BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/build-tools/$BUILD_TOOLS_VERSION" >> $GITHUB_PATH

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: odfiz-final-signed
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
