name: Build APK
on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "android-build"

      - name: Install cargo-ndk
        run: |
          if ! command -v cargo-ndk &> /dev/null; then
            cargo install cargo-ndk
          fi

      - name: Build Rust Lib (Release)
        run: |
          mkdir -p app/src/main/jniLibs/arm64-v8a
          cargo ndk -t arm64-v8a -o app/src/main/jniLibs/ build --release

      - name: Build APK with Gradle (Release)
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: odfiz-final-signed
          # Mengambil output file yang sudah ditandatangani
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
